apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    enviroment: test
    app: nginx
spec:
  containers:
  - name: web
    image: borisluchnikov/kube-web-app:latest
    volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
  - name: index-html-creator
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app
  volumes:
    - name: app
      emptyDir: {}